/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.O6926_yogi_ta.project.View;

import com.O6926_yogi_ta.project.Controller.Controller;
import com.O6926_yogi_ta.project.Object.Cabang_06926;
import com.O6926_yogi_ta.project.Object.Konsumen_06926;
import com.O6926_yogi_ta.project.Object.Jabatan;
import com.O6926_yogi_ta.project.Object.Pegawai_06926;
import com.O6926_yogi_ta.project.Object.Riwayat;
import com.O6926_yogi_ta.project.Object.Unit_06926;
import com.O6926_yogi_ta.project.View.*;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DFA-Agent02
 */
public class Admin_view extends javax.swing.JFrame {
    Controller control = new Controller();
    static int i = 0;
    public static String nama_admin,cabang;
    
    public Admin_view(String nama_admin,String cabang) throws SQLException {
       initComponents();
       this.nama_admin=nama_admin;
       this.cabang=cabang;
        this.showNamaAdmin(nama_admin);
        this.showNamaCabang(cabang);
        this.showcbNamaKolektor();
        this.showTblListCollector();
        this.showTblListKons();
    }

//    private Admin_view() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNamacabang = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNamakonsumen = new javax.swing.JTextField();
        tfNoKontrak = new javax.swing.JTextField();
        cbNamakolektor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListkonskolektor = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblListKonsumen = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jlNamacabang.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel1.setText("Nama Konsumen");

        jLabel2.setText("No Kontrak");

        jLabel5.setText("Nama Kolektor");

        cbNamakolektor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbNamakolektor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNamakolektorActionPerformed(evt);
            }
        });

        tblListkonskolektor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListkonskolektor);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAddUser.setText("Tambah User");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete User");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tblListKonsumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblListKonsumen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfNoKontrak)
                            .addComponent(cbNamakolektor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfNamakonsumen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jlNamacabang, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 212, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddUser)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jlNamacabang)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfNamakonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tfNoKontrak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbNamakolektor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jScrollPane1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbNamakolektorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNamakolektorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNamakolektorActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        try {
            new Add_user().show();
            setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Admin_view.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            new Login_view().show();
            setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Admin_view.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       String NikColl = Controller.arrPegawai.get(this.tblListkonskolektor.getSelectedRow()+1).getNIK();
       
        System.out.println(NikColl);
       control.deleteDataJabatan(NikColl);
       control.deleteDataPegawai(NikColl);
        try {
            control = new Controller();
        } catch (SQLException ex) {
            Logger.getLogger(Admin_view.class.getName()).log(Level.SEVERE, null, ex);
        }
       JOptionPane.showMessageDialog(null, "User Telah Dihapus", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
       this.showTblListCollector();
        try {
            this.showcbNamaKolektor();
        } catch (SQLException ex) {
            Logger.getLogger(Admin_view.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String NIKe = Controller.arrPegawai.get(this.tblListkonskolektor.getSelectedRow()+1).getNIK();
        System.out.println(NIKe);
        new Form_update(NIKe, nama_admin, cabang).show();
        setVisible(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String Nakos = this.tfNamakonsumen.getText();
        String NoKont = this.tfNoKontrak.getText().trim();
        String NaColl = Controller.arrPegawai.get(this.cbNamakolektor.getSelectedIndex()+1).getNama_pegawai();
    //    System.out.println(NaColl);
        control.setNamaPenagih(NoKont,NaColl); 
        try {
            control= new Controller();
        } catch (SQLException ex) {
            Logger.getLogger(Admin_view.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Berhasil menyimpan perubaan", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Admin_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Admin_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Admin_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Admin_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Admin_view(String nama_admin, Integer kode).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbNamakolektor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlNamacabang;
    private javax.swing.JTable tblListKonsumen;
    private javax.swing.JTable tblListkonskolektor;
    private javax.swing.JTextField tfNamakonsumen;
    private javax.swing.JTextField tfNoKontrak;
    // End of variables declaration//GEN-END:variables

    private void showNamaAdmin(String nama_admin) {
       JLabel namaJdl_Admin = new JLabel(nama_admin.toUpperCase());
       namaJdl_Admin.setBounds(5, 5, 300, 80);
       namaJdl_Admin.setFont(new Font("Times new roman", 1, 72));
       add(namaJdl_Admin);
    }

    private void showNamaCabang(String cabang) {
        JLabel namaJdl_cabang = new JLabel(cabang.toUpperCase());
        namaJdl_cabang.setBounds(5, 20,200,150);
        namaJdl_cabang.setFont(new Font("Times new roman", 1, 14));
        add(namaJdl_cabang);
        }


    private void showcbNamaKolektor() throws SQLException {
        //System.out.println(Controller.arrPegawai.size());
        DefaultComboBoxModel dcbmKollektor = new DefaultComboBoxModel();
    for(int i=0;i<Controller.arrPegawai.size();i++){
           // System.out.println(Controller.arrJabatan.size());
            if("collector".equals(Controller.arrJabatan.get(i).getNama_jabatan())){
            dcbmKollektor.addElement(Controller.arrPegawai.get(i).getNama_pegawai());
            }
    }
    this.cbNamakolektor.setModel(dcbmKollektor);
    }

    private void showTblListCollector() {
        DefaultTableModel dtmListColector = new DefaultTableModel(new String[]{"Nama Pegawai","NIK", "TELP","STATUS PEGAWAI"},0);
        dtmListColector.setRowCount(0);
        for(int i=0;i<Controller.arrPegawai.size();i++){
         //   System.out.println(Controller.arrJabatan.size());
            if("collector".equals(Controller.arrJabatan.get(i).getNama_jabatan())){
            dtmListColector.addRow(new String[]{Controller.arrPegawai.get(i).getNama_pegawai(),Controller.arrPegawai.get(i).getNIK(),Controller.arrPegawai.get(i).getNo_telp(),Controller.arrPegawai.get(i).getStatus_karyawan()});
            }            
    }
        this.tblListkonskolektor.setModel(dtmListColector);
    }

    private void showTblListKons() {
        DefaultTableModel dtmListKons = new DefaultTableModel(new String[]{"Nama Konsumen","No Kontrak"},0);
        dtmListKons.setRowCount(0);
        for (int j=0;j<Controller.arrKonsumen.size();j++){
            dtmListKons.addRow(new String[]{Controller.arrKonsumen.get(j).getNama_konsumen(),Controller.arrKonsumen.get(j).getNo_kontrak().toString()});
        }
        this.tblListKonsumen.setModel(dtmListKons);
    }

}
