package com.O6926_yogi_ta.project.View;

import java.sql.ResultSet;
import com.O6926_yogi_ta.project.Connection.Connectiion;
import java.sql.SQLException;
import com.O6926_yogi_ta.project.View.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author DFA-Agent02
 */
public class Detail_konsumen extends javax.swing.JFrame {
Connectiion conect = new Connectiion();
public static String napeg1,nacab1,Teks;
    /**
     * Creates new form Detail_konsumen
     */
    public Detail_konsumen(String Primer,String napeg,String nacab) throws SQLException {
        initComponents();
        this.napeg1=napeg;
        this.nacab1=nacab;
        this.showDetail(Primer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Detail Konsumen");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Angsuran Sudah Di Ambil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        new Collector_view(napeg1, nacab1).show();
        setVisible(false);
    } catch (SQLException ex) {
        Logger.getLogger(Detail_konsumen.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Detail_konsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Detail_konsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Detail_konsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Detail_konsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Detail_konsumen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private void showDetail(String Primer) throws SQLException {
        
        ResultSet rs = this.conect.GetData("select a.nama_konsumen as nama_konsumen, a.no_kontrak as no_kontrak, a.no_telp as no_telp, a.penagih as penagih, a.alamat_konsumen as alamat_konsumen, b.plat_nomer as plat_nomer, b.merk as merk, b.tipe as tipe, b.golongan as golongan, c.denda as denda, c.angsuran as angsuran, c.tgl_jt_tempo as tgl_jt_tempo, c.terlambat_hari as terlambat_hari from konsumen_06926 a join unit_06926 b on a.no_kontrak = b.no_kontrak join rwyt_konsumen_06926 c on a.no_kontrak = c.no_kontrak where a.no_kontrak = "+Primer);
        System.out.println(rs+"\n"+Primer);
        while(rs.next()){
        Teks = ""
                    +"\nNama Konsumen            : "+rs.getString("nama_konsumen")
                    +"\nNo Kontrak                   : "+rs.getString("no_kontrak")
                    +"\nNo Telp                        : "+rs.getString("no_telp")
                    +"\nNama Kolektor               : "+rs.getString("penagih")
                    +"\nAlamat Konsumen          : "+rs.getString("alamat_konsumen")
                    +"\nPlat Nomer                  : "+rs.getString("plat_nomer")
                    +"\nMerk Unit                       : "+rs.getString("merk")
                    +"\nTipe Unit                : "+rs.getString("tipe")
                    +"\nMotor/Mobil/Truck        : "+rs.getString("golongan")
                    +"\nDenda                    : "+rs.getInt("denda")
                    +"\nAngsuran                 : "+rs.getString("angsuran")
                    +"\nJatuh Tempo tgl          : "+rs.getInt("tgl_jt_tempo")
                    +"\nTerlambat                : "+rs.getInt("terlambat_hari")+" hari";
        }
        this.jTextArea1.setText(Teks);
        
    }
}
